<?php
/** @var Neosolax\Giftregistry\Block\Item\Index $block */
?>

<p>This is Giftregistry Item Page</p>

<p> need to list down item list and have to identify what are the item already purchased </p>
<?php if ($block->hasGiftregistryItems()) : ?>
<table>
    <tr>
        <th>Gift Registry ID</th>
        <th>Product ID</th>
    </tr>
<?php
$collection = $block->getResult();
foreach ($collection as $item) {
    ?>
    <tr>
        <td><?php echo $item->getData('giftregistry_id'); ?></td>
        <td><?php echo $item->getData('product_id'); ?></td>
        <td><img src="<?php echo $block->getProductImageUrl($item->getData('product_id')); ?> " /></td>
        <td>
            <a href="<?php echo $block->getUrl('giftregistry/item/index') . 'id/' . $item->getData('giftregistry_id'); ?>"><button>Add to Cart</button></a>
            <a href="<?php echo $block->getUrl('giftregistry/index/delete') . 'id/' . $item->getData('giftregistry_id'); ?>" ><button>Delete</button></a>
        </td>>
    </tr>
    <?php
} ?>
</table>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have no items in your gift registry.')) ?></span></div>
<?php endif ?>

<div class="actions-toolbar">
    <div class="secondary">
        <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back">
            <span><?= $block->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
