<?php

/** @var \Magento\Wishlist\Block\Customer\Wishlist $block */
?>

        <?php if ($block->hasWishlistItems()) : ?>
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?= $block->getChildHtml('items') ?>
        <?php else : ?>
            <div class="message info empty"><span><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></span></div>
        <?php endif ?>
        <div class="actions-toolbar">
            <div class="secondary">
                <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back">
                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                </a>
            </div>
        </div>


